### Schema
CREATE DATABASE rr_DB;

USE rr_DB;

CREATE TABLE beacons(
  id INT NOT NULL AUTO_INCREMENT,
  user_id INTEGER NOT NULL,
  name VARCHAR(255) NOT NULL,
  activity VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  rallies INTEGER NOT NULL,
  riots INTEGER NOT NULL,
  ageMin INTEGER NOT NULL,
  ageMax INTEGER NOT NULL,
  gender VARCHAR(255) NOT NULL,
  lat DECIMAL (16,6),
  lng DECIMAL (16,6),
  population INTEGER NOT NULL,
  timeCreated TIMESTAMP,
  PRIMARY KEY (id)
);

SELECT * FROM beacons;
